import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "$/lib/providers/QueryClientProvider";
import { PropsWithChildren } from "react";
import Footer from "$/lib/components/common/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  modal: React.ReactNode;
};

export default function RootLayout({
  modal,
  children,
}: PropsWithChildren<Props>) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body className={inter.className}>
          {children}
          {modal}
          <Footer />
        </body>
      </QueryClientProvider>
    </html>
  );
}
