import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/lib/providers/QueryClientProvider";

// const inter = Roboto({
//   subsets: ["latin"],
//   weight: ["100", "400", "700"],
// });

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
